package BananaFructa.somnium.pyinterpreter;

import net.minecraft.util.Tuple;

import javax.swing.text.Utilities;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
Why is there a whole python interpreter in a minecraft mod?
1) The game needs to interpret arbitrary python code generated by an LLM;
2) The game needs to interpret arbitrary python code passed through a network port;
3) Python is simple and widely used thus the LLM will have an easier time with it;
4) The interpreted code somehow needs to link to java functions to interact with the game;
Basic python interpreter. Does not support imports nor OS calls. A subset of the math library is implemented by default.
Implemented features:
 - operators
 - variables
 - functions
 - if statements
 - loops
 - lists
 - math functions imported natively (without math. library)
 - lambda expressions
 - ternary operators
 */
public class JavaPythonShadower {

    public static String globalCodeFunction = "_global";

    public static ShadowedPythonCode interpret(String code, HashMap<String, List<String>> linkedSymbolicFunctions) {
        code = removeComments(code);
        Definitions definitions = new Definitions();
        // code in the global field gets thrown into a "__global__" method that can be executed
        definitions.put(globalCodeFunction, new FunctionDefinition(globalCodeFunction, new ArrayList<>()));
        Stack<ScopeInfo> scopes = new Stack<>();
        scopes.push(new ScopeInfo(globalCodeFunction, 0));
        PointedString text = new PointedString(code);
        List<Integer> spaceCounts = new ArrayList<>();
        while (text.hasNext()) {
            spaceCounts.add(spaceCount(text.nextLine()));
        }

        List<List<String>> tokens = tokeniser(code);
        PointedTokenSpace tokenSpace = PointedTokenSpace.fromMultiLine(tokens);
        while (tokenSpace.hasLine()) {

            int spaces = spaceCounts.get(tokenSpace.line);
            if (scopes.peek().minSpaces == -1 && spaces <= scopes.get(scopes.size() - 2).minSpaces)
                throw new RuntimeException("LID Python: Empty function body.");
            else if (scopes.peek().minSpaces == -1) scopes.peek().minSpaces = spaces;

            while (scopes.peek().minSpaces > spaces) scopes.pop();

            String startingToken = tokenSpace.peek();

            if (startOfFunctionDefinition(startingToken)) { // FUNCTION DECLARATION

                if (tokenSpace.lineLength() < 2) throw new RuntimeException("LID Python: Hanging def statement.");
                tokenSpace.next();
                String functionName = tokenSpace.next();
                if (!isWord(functionName)) throw new RuntimeException("LIP Python: Invalid function name.");
                List<String> params = commaSplit(getTokenInBetweenBrackets(tokenSpace));
                if (params.stream().anyMatch((e) -> !isWord(e)))
                    throw new RuntimeException("LIP Python: Invalid parameter(s) name.");
                if (!isColon(tokenSpace.peekLast()))
                    throw new RuntimeException("LIP Python: Expected function declaration to end in ':'");
                definitions.put(functionName, new FunctionDefinition(functionName, params));
                scopes.push(new ScopeInfo(functionName, -1));

            } else if (startOfIfStatement(startingToken)) {

                //if (!isColon(tokenSpace.peekLast()))
                //    throw new RuntimeException("LIP Python: Expected if declaration to end in ':'");
                tokenSpace.next();
                List<String> conditionTokens = collectTokensUntil(tokenSpace, JavaPythonShadower::isColon);
                ASTNode condition = parseExpression(PointedTokenSpace.fromSingleLine(conditionTokens),definitions,linkedSymbolicFunctions);
                String trueScope = generateScopeName(definitions.scopeCounter++);
                ASTSwitch ifStatement = new ASTSwitch(startingToken, condition, trueScope);
                addToScope(definitions, scopes.peek(), ifStatement);
                definitions.put(trueScope, new ScopeDefinition(trueScope));
                scopes.push(new ScopeInfo(trueScope, -1));

            } else if (startOfElse(startingToken)) {

                if (!isColon(tokenSpace.peekLast()))
                    throw new RuntimeException("LIP Python: Expected else declaration to end in ':'");
                tokenSpace.next();
                ASTNode last = scopes.peek().lastAddedNode;
                if (last instanceof ASTSwitch) {
                    ASTSwitch sw = (ASTSwitch) last;
                    if (sw.falseScope == null) {
                        String falseScope = generateScopeName(definitions.scopeCounter++);
                        sw.falseScope = falseScope;
                        scopes.peek().lastAddedNode = null;
                        definitions.put(falseScope, new ScopeDefinition(falseScope));
                        scopes.push(new ScopeInfo(falseScope, -1));
                    } else throw new RuntimeException("LID Python: Else but no if statement.");
                } else throw new RuntimeException("LID Python: Else but no if statement.");

            } else if (startOfElif(startingToken)) {
                //if (!isColon(tokenSpace.peekLast()))
                //    throw new RuntimeException("LIP Python: Expected elif declaration to end in ':'");
                tokenSpace.next();
                ASTNode last = scopes.peek().lastAddedNode;
                if (last instanceof ASTSwitch) {
                    List<String> conditionTokens = collectTokensUntil(tokenSpace, JavaPythonShadower::isColon);
                    ASTNode condition = parseExpression(PointedTokenSpace.fromSingleLine(conditionTokens),definitions,linkedSymbolicFunctions);

                    ASTSwitch sw = (ASTSwitch) last;
                    String elifScope = generateScopeName(definitions.scopeCounter++);
                    sw.elifs.add(new Tuple<>(condition, elifScope));

                    definitions.put(elifScope, new ScopeDefinition(elifScope));
                    scopes.push(new ScopeInfo(elifScope, -1));
                } else throw new RuntimeException("LID Python: Elif but no if statement.");
            } else if (isReturn(startingToken)) {
                tokenSpace.next();
                ASTNode returnExp = parseExpression(tokenSpace,definitions,linkedSymbolicFunctions);
                ASTReturn ret = new ASTReturn(startingToken);
                ret.returnExp = returnExp;
                addToScope(definitions, scopes.peek(), ret);
            } else if (isFor(startingToken)) {
                //if (!isColon(tokenSpace.peekLast()))
                //    throw new RuntimeException("LIP Python: Expected for declaration to end in ':'");
                tokenSpace.next();
                ASTFor forDec = new ASTFor(startingToken);
                // for (1) <name> (2) in (3) <exp> (4) : (5)
                //if (tokenSpace < 5) throw new RuntimeException("LIP Python: Incomplete for declaration");
                String var = tokenSpace.next();
                if (!isWord(var)) throw new RuntimeException("LIP Python: Iterator has invalid variable name");
                forDec.var = var;
                if (!tokenSpace.next().equals("in")) throw new RuntimeException("LIP Python: Expected in after iterator.");
                List<String> listTokens = collectTokensUntil(tokenSpace, JavaPythonShadower::isColon);
                forDec.list = parseExpression(PointedTokenSpace.fromSingleLine(listTokens),definitions,linkedSymbolicFunctions);
                forDec.scope = generateScopeName(definitions.scopeCounter++);

                addToScope(definitions, scopes.peek(), forDec);
                definitions.put(forDec.scope, new ScopeDefinition(forDec.scope));
                scopes.push(new ScopeInfo(forDec.scope, -1));
            } else if (isBreak(startingToken)) {
                if (tokenSpace.lineLength() != 1) throw new RuntimeException("LID Python: Did not expect anything after break.");
                ASTBreak b = new ASTBreak(startingToken);
                addToScope(definitions, scopes.peek(), b);
            } else if (isWhile(startingToken)) {
                //if (!isColon(tokenSpace.peekLast()))
                //    throw new RuntimeException("LIP Python: Expected while declaration to end in ':'");
                tokenSpace.next();
                // while (1) <statement>(2) :(3)
                //if (tokens.size() < 3) throw new RuntimeException("LIP Python: Incomplete while declaration.");
                ASTWhile astWhile = new ASTWhile(startingToken);
                List<String> statement = collectTokensUntil(tokenSpace, JavaPythonShadower::isColon); // TODO: this will need to return the whole thing
                astWhile.scope = generateScopeName(definitions.scopeCounter++);
                astWhile.statement = parseExpression(PointedTokenSpace.fromSingleLine(statement),definitions,linkedSymbolicFunctions);

                addToScope(definitions, scopes.peek(), astWhile);
                definitions.put(astWhile.scope, new ScopeDefinition(astWhile.scope));
                scopes.push(new ScopeInfo(astWhile.scope, -1));
            } else if (isPass(startingToken)) {
                // Do nothing
            }  else {
                ASTNode expression = parseExpression(tokenSpace,definitions,linkedSymbolicFunctions);
                addToScope(definitions, scopes.peek(), expression);
            }

            tokenSpace.nextLine();

        }

        //List<ASTNode> global = ((FunctionDefinition)definitions.get("test")).expressions;
        //for (ASTNode n : global) n.print(0);

        return new ShadowedPythonCode(code, definitions);
    }

    public static int spaceCount(String line) {
        int i = 0;
        for (char c : line.toCharArray()) {
            switch (c) {
                case ' ':
                    i += 1;
                    break;
                case '\t':
                    i += 4;
                    break;
                default:
                    return i;
            }
        }
        return i;
    }

    public static void addToScope(Definitions definitions, ScopeInfo scopeInf, ASTNode exp) {
        scopeInf.lastAddedNode = exp;
        ExpressionGroup scope = definitions.get(scopeInf.functionScopeName);
        if (scope instanceof FunctionDefinition) ((FunctionDefinition)definitions.get(scopeInf.functionScopeName)).expressions.add(exp);
        else if (scope instanceof ScopeDefinition) ((ScopeDefinition)definitions.get(scopeInf.functionScopeName)).expressions.add(exp);
    }

    public static String generateScopeName(int identifier) {
        return "_internal_scope_" + identifier;
    }
    public static String generateFunctionName(int identifier) {
        return "_internal_function_"+identifier;
    }

    public static boolean isLetter(char c) {
        return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || c == '_';
    }

    public static boolean isNumber(char c) {
        return '0' <= c && c <= '9';
    }

    public static boolean startOfFunctionDefinition(String token) {
        return token.equals("def");
    }

    public static boolean isDoubleQute(char c) {
        return c == '"';
    }

    public static boolean isSingleQutoe(char c) {
        return c == '\'';
    }

    public static boolean startOfIfStatement(String token) {
        return token.equals("if");
    }

    public static boolean startOfElse(String token) {
        return token.equals("else");
    }

    public static boolean isFor(String token) {
        return token.equals("for");
    }

    public static boolean startOfElif(String token) {
        return token.equals("elif");
    }

    public static boolean isColon(String token) {
        return token.equals(":");
    }

    public static boolean isReturn(String token) {
        return token.equals("return");
    }

    public static boolean isListStart(String token) {
        return token.equals("[");
    }

    public static boolean isListEnd(String token) {
        return token.equals("]");
    }

    public static boolean isBreak(String token) {
        return token.equals("break");
    }

    public static boolean isWhile(String token) {
        return token.equals("while");
    }

    public static boolean isPass(String token) {
        return token.equals("pass");
    }

    public static boolean isComment(String token) {
        return token.equals("#");
    }

    public static boolean isLambda(String token) {
        return token.equals("lambda");
    }

    public static List<String> collectTokensUntil(PointedTokenSpace tokenSpace, Function<String,Boolean> f) {
        List<String> collected = new ArrayList<>();
        do {
            while (tokenSpace.hasNext()) {
                if (f.apply(tokenSpace.peek())) {
                    return collected;
                }
                collected.add(tokenSpace.next());
            }
            tokenSpace.nextLine();
        } while (tokenSpace.hasLine());
        return collected;
    }

    public static List<String> getTokenInBetweenBrackets(PointedTokenSpace tokens) {
        if (!tokens.hasNext()) throw new RuntimeException("LID Python: Expected bracket.");
        if (!isOpenBracket(tokens.next())) throw new RuntimeException("LID Python: Expected bracket.");
        List<String> inner = collectTokensUntil(tokens, JavaPythonShadower::isClosedBracket);
        // If the last collected is the last in the token then there is no )
        // TODO: refactor this
        if (inner.isEmpty() && tokens.hasNext() && (!isClosedBracket(tokens.peek()))) throw new RuntimeException("LID Python: Bracket not closed.");
        else if (!inner.isEmpty() && inner.get(inner.size()-1).equals(tokens.peekLast())) throw new RuntimeException("LID Python: Bracket not closed.");
        return inner;
    }

    public static List<String> commaSplit(List<String> tokens) {
        boolean comma = false;
        List<String> split = new ArrayList<>();
        for (int i = 0;i < tokens.size();i++) {
            if (comma) {
                if (!isComma(tokens.get(i))) throw new RuntimeException("LID Python: Expected comma in between parameters");
                comma = false;
            } else {
                split.add(tokens.get(i));
                comma = true;
            }
        }
        return split;
    }

    public static int isOperator(String c) {
        switch (c) {
            case "==":
            case "<=":
            case "!=":
            case ">=":
            case ">":
            case "<":
                return 6;
            case "or":
                return 3;
            case "and":
                return 4;
            case "not":
                return 5;
            case "=":
                return 0;
            case "in":
                return 2;
            case "+":
            case "-":
                return 11;
            case "*":
            case "/":
                return 12;
            case "%":
                return 13;
            case "**":
                return 14;
            case ".":
                return 15;
            default:
                return -1; // not an operator
        }
    }

    public static boolean isUnary(String s) {
        return s.equals("not");
    }

    public static boolean isNumber(String s) {
        if (s.isEmpty()) return false;
        if (s.charAt(0) == '.') return false;// this is valid but makes attribute code easier
        if (s.startsWith("0x")) {
            for (int i = 2;i < s.length();i++) {
                if (!(isLetter(s.charAt(i)) || isNumber(s.charAt(i)))) return false;
            }
        } else {
            for (char c : s.toCharArray()) if (!isNumber(c) && c != '.') return false;
        }
        return true;
    }

    public static boolean isWord(String s) {
        if (!isLetter(s.charAt(0))) return false;
        for (char c : s.toCharArray()) if (!(isLetter(c) || isNumber(c))) return false;
        return true;
    }

    public static boolean isOpenBracket(String s) {
        return s.equals("(");
    }

    public static boolean isClosedBracket(String s) {
        return s.equals(")");
    }

    public static boolean isComma(String s) {
        return s.equals(",");
    }

    public static String iterateUntil(PointedString string, Function<Character, Boolean> condition) {
        String data = "";
        while (string.hasNext() && condition.apply(string.peek())) data += string.next();
        return data;
    }

    public static boolean isString(String token) {
        return isDoubleQute(token.charAt(0)) || isSingleQutoe(token.charAt(0));
    }

    // TODO: this does not take into account if # is inside a string
    public static String removeComments(String s) {
        String left = "";
        for (String line : s.split("\n")) {
            boolean content = false;
            for (int i = 0;i < line.length();i++) {
                if (!content && (line.charAt(i) == ' ' || line.charAt(i) == '\t')) continue;
                if (line.charAt(i) == '#') {
                    if (content) {
                        left += line.substring(0,i) + '\n';
                    }
                    break;
                } else {
                    content = true;
                    if (i == line.length() - 1) {
                        left += line + '\n';
                    }
                }
            }
        }
        return left;
    }

    public static List<List<String>> tokeniser(String code) {

        String[] lines = code.split("\n");
        List<List<String>> allTokens = new ArrayList<>();
        for (String line : lines) {
            PointedString s = new PointedString(line);
            List<String> tokens = new ArrayList<>();
            while (s.hasNext()) {
                char start = s.peek();
                boolean trailingWhiteSpace = false;
                while (start == ' ' || start == '\t' || start == '\r' || start == '\n') {
                    s.next(); // skip white spaces
                    if (!s.hasNext()) {
                        trailingWhiteSpace = true;
                        break;
                    }
                    start = s.peek();
                }
                if (trailingWhiteSpace) break;
                if (isLetter(start)) tokens.add(iterateUntil(s, (c) -> { // word
                    return isLetter(c) || isNumber(c);
                }));
                else if (isNumber(start)) {
                    if (start == '0' && s.hasNext(1) && s.peek(1) == 'x') {
                        String tks = "" + s.next() + s.next();
                        tokens.add(tks + iterateUntil(s, (c) -> {
                            return isNumber(c) || isLetter(c);
                        }));
                    } else {
                        tokens.add(iterateUntil(s, (c) -> {
                            return isNumber(c) || c == '.' || c == 'x';
                        }));
                    }
                }
                else if (isDoubleQute(start)) {
                    s.next();
                    // TODO: this string parsing doesn't take any special characters into account
                    String text = start + iterateUntil(s,(c) -> {
                        return !isDoubleQute(c);
                    });
                    text += s.next();
                    tokens.add(text);
                } else if (isSingleQutoe(start)) {
                    s.next();
                    // TODO: this string parsing doesn't take any special characters into account
                    String text = start + iterateUntil(s,(c) -> {
                        return !isSingleQutoe(c);
                    });
                    text += s.next();
                    tokens.add(text);
                }
                else {
                    String tf = Character.toString(s.next());
                    if (s.hasNext()) { // this is to support operators with 2 characters
                        String tff = tf + Character.toString(s.peek());
                        if (isOperator(tff) != -1) {
                            tokens.add(tff);
                            s.next();
                        } else tokens.add(tf);
                    } else tokens.add(tf);
                }

            }
            if (!tokens.isEmpty()) allTokens.add(tokens);
        }
        return allTokens;
    }

    public static boolean isExpressionTerm(ASTNode n) {
        return n instanceof ASTNumber || n instanceof ASTVariable || n instanceof ASTFunction || n instanceof ASTList || n instanceof ASTTuple || n instanceof ASTString || n instanceof ASTLambda || n instanceof ASTConditional;
    }

    public static boolean pushOperand(ASTNode head, ASTNode leaf) {
        if (!(head instanceof ASTOperator)) return false;
        if (!((ASTOperator) head).full()) {
            head.children.add(leaf);
            leaf.parent = head;
            return true;
        } else {
            if (head.children.get(((ASTOperator) head).unary ? 0 : 1) instanceof ASTOperator) return pushOperand(head.children.get(((ASTOperator) head).unary ? 0 : 1),leaf);
            else return false;
        }
    }

    private static void addChild(ASTNode parent, ASTNode child,Definitions definitions) {
        child.parent = parent;
        parent.children.add(child);
    }

    public static ASTNode pushOperator(ASTNode head, ASTNode leaf, Definitions definitions) {
        if (!(head instanceof ASTOperator)) { // If the head is an operand and the leaf is an operator
            leaf.parent = head.parent;
            addChild(leaf,head,definitions);
            //head.parent = leaf;
            //leaf.children.add(head);

            if (leaf.parent != null) {
                leaf.parent.children.remove(((ASTOperator) leaf.parent).unary ? 0 : 1);
                //leaf.parent.children.add(leaf);
                addChild(leaf.parent,leaf,definitions);
            }
            return leaf;
        } else if (((ASTOperator)leaf).precedence > ((ASTOperator)head).precedence) { // if two operators need to be joined where the leaf has higher precedence
            // This error is a bit harder to implement I guess it will just have to be sorted at runtime, by a bad operand type thing;
            //if (!((ASTOperator) head).full() && !((ASTOperator) leaf).unary) throw new RuntimeException("LID Python: Operator one after the other");
            if (((ASTOperator) head).full()) pushOperator(head.children.get(((ASTOperator) head).unary ? 0 : 1),leaf,definitions); // Check the right leaf of the head to push the leaf
            else {
                //head.children.add(leaf); // If the operator has children available then just push it
                //leaf.parent = head;
                addChild(head,leaf,definitions);
            }
            return head;
        } else {
            leaf.parent = head.parent; // if the precedence of the leaf is smaller it can be pushed
            addChild(leaf,head,definitions);
            //head.parent = leaf;
            //leaf.children.add(head);
            if (leaf.parent != null) {
                leaf.parent.children.remove(((ASTOperator) leaf.parent).unary ? 0 : 1);
                //leaf.parent.children.add(leaf);
                addChild(leaf.parent,leaf,definitions);
            }
            return leaf;
        }
    }

    static ASTNode pushToAST(ASTNode head, ASTNode other, Definitions definitions) {
        if (other instanceof ASTOperator) return pushOperator(head, other, definitions);
        // If the incoming operator has all of its children filled it must mean it was processed first, which happens in the case of it being place in brackets
        if (isExpressionTerm(other) || (other instanceof ASTOperator && ((ASTOperator)other).full())) {
            if (!pushOperand(head,other)) throw new RuntimeException("LID Python: Term one after the other");
            return head;
        }
        throw new RuntimeException("LID Python: Invalid symbol sequence.");
    }

    public static List<String> collectContainedTokens(PointedTokenSpace tokens, Function<String,Boolean> begin, Function<String,Boolean> end) {
        int nesting = 1;
        List<String> between = new ArrayList<>();
        do {
            while (tokens.hasNext() && nesting != 0) {
                if (begin.apply(tokens.peek())) nesting++;
                if (end.apply(tokens.peek())) nesting--;
                if (nesting != 0) between.add(tokens.peek());
                tokens.next();
            }
            if (nesting == 0) break;
            else tokens.nextLine();
        } while (tokens.hasLine());
        if (nesting != 0) throw new RuntimeException("LID Python: Bracket not closed");
        return between;
    }

    public static List<ASTNode> collectContainedList(PointedTokenSpace tokens, Function<String,Boolean> begin, Function<String,Boolean> end, Definitions definitions, HashMap<String, List<String>> linkedSymbolicFunctions) {
        List<String> between = collectContainedTokens(tokens,begin,end);

        List<String> parameterExpression = new ArrayList<>();
        List<ASTNode> parameterNodes = new ArrayList<>();

        int nestingParams = 0;
        int nestingList = 0;
        boolean inLambda = false;

        for (String t : between) {
            if (isComma(t) && nestingParams == 0 && nestingList == 0 && !inLambda) {
                parameterNodes.add(parseExpression(PointedTokenSpace.fromSingleLine(parameterExpression),definitions,linkedSymbolicFunctions));
                parameterExpression.clear();
            } else {
                if (isOpenBracket(t)) nestingParams++;
                if (isClosedBracket(t)) nestingParams--;
                if (isListStart(t)) nestingList++;
                if (isListEnd(t)) nestingList--;
                if (isLambda(t)) inLambda = true;
                if (inLambda && isColon(t)) inLambda = false;
                parameterExpression.add(t);
            }
        }
        if (!parameterExpression.isEmpty()) {
            parameterNodes.add(parseExpression(PointedTokenSpace.fromSingleLine(parameterExpression),definitions,linkedSymbolicFunctions));
            parameterExpression.clear();
        }

        return parameterNodes;
    }

    public static ASTNode parseExpression(PointedTokenSpace tokens, Definitions definitions, HashMap<String, List<String>> linkedSymbolicFunctions) {
        ASTNode head = null;
        ASTNode last = null;
        while(tokens.hasNext()) {
            String token = tokens.next();
            ASTNode other = null;
            if (isNumber(token)) {
                other = new ASTNumber(token);
            } else if (isOperator(token) != -1) {
                if (!(last instanceof ASTNumber || last instanceof ASTFunction || last instanceof ASTVariable) && token.equals("-")) {
                    ASTOperator op = new ASTOperator(token, isOperator(token));
                    op.unary = true;
                    other = op;
                } else {
                    ASTOperator op = new ASTOperator(token, isOperator(token));
                    op.unary = isUnary(token);
                    other = op;
                }
            } else if (isLambda(token)) {
                List<String> params = commaSplit(collectTokensUntil(tokens, JavaPythonShadower::isColon));
                tokens.next();
                String funcName = generateFunctionName(definitions.scopeCounter++);
                FunctionDefinition functionDefinition = new FunctionDefinition(funcName,params);
                definitions.put(funcName,functionDefinition);
                ASTLambda lambda = new ASTLambda(token);
                lambda.internalFunctionName = funcName;
                ASTNode innerLambda = parseExpression(tokens,definitions,linkedSymbolicFunctions);
                ASTReturn lambdaReturn = new ASTReturn("return");
                lambdaReturn.returnExp = innerLambda;
                definitions.get(funcName).expressions.add(lambdaReturn);
                other = lambda;
            } else if (isWord(token)) {
                if (!tokens.hasNext()) other = new ASTVariable(token);
                else if (isOpenBracket(tokens.peek())) {
                    tokens.next();
                    other = new ASTFunction(token);
                    List<ASTNode> params = collectContainedList(tokens,JavaPythonShadower::isOpenBracket,JavaPythonShadower::isClosedBracket,definitions,linkedSymbolicFunctions);
                    List<String> parameterNames = null;
                    if (definitions.containsKey(token)) {
                        if (((FunctionDefinition)definitions.get(token)).parameters.size() > params.size()) throw new RuntimeException("LID Python: Too many parameters for function call.");
                        if (((FunctionDefinition)definitions.get(token)).parameters.size() < params.size()) throw new RuntimeException("LID Python: Too little parameters for function call.");
                        parameterNames = ((FunctionDefinition)definitions.get(token)).parameters;
                    }
                    if (linkedSymbolicFunctions.containsKey(token)) {
                        if (linkedSymbolicFunctions.get(token).size() > params.size()) throw new RuntimeException("LID Python: Too many parameters for function call.");
                        if (linkedSymbolicFunctions.get(token).size() < params.size()) throw new RuntimeException("LID Python: Too little parameters for function call.");
                        parameterNames = linkedSymbolicFunctions.get(token);
                    }
                    HashMap<String,ASTNode> keywordArguments = new HashMap<>();
                    boolean endPositional = false;
                    for (ASTNode param : params) {
                        if (param instanceof ASTOperator && param.name.equals("=")) {
                            endPositional = true;
                            ASTOperator op = (ASTOperator) param;
                            if (!op.full()) throw new RuntimeException("LID Python: Equal hanging in keyword argument.");
                            if (parameterNames == null) throw new RuntimeException("LID Python: Function either doesn't exist or is not symbolically linked. Keyword parameters are not supported.");
                            if (keywordArguments.containsKey(op.children.get(0).name)) throw new RuntimeException("LID Python: Keyword argument already defined.");
                            keywordArguments.put(op.children.get(0).name,op.children.get(1));
                        } else {
                            if (endPositional) throw new RuntimeException("LID Python: Positional argument after keyword argument.");
                            other.children.add(param);
                            param.parent = other;
                        }
                    }
                    if (parameterNames != null) {
                        if (other.children.size() + keywordArguments.size() > parameterNames.size()) throw new RuntimeException("LID Python: Too many parameters for function call.");
                        if (other.children.size() + keywordArguments.size() < parameterNames.size()) throw new RuntimeException("LID Python: Too little parameters for function call.");
                        int diff = parameterNames.size() - other.children.size();
                        for (int i = 0;i < diff;i++) other.children.add(null);
                        for (String paramName : keywordArguments.keySet()) {
                            if (!parameterNames.contains(paramName)) throw new RuntimeException("LID Python: Parameter name doesn't exist.");
                            other.children.set(parameterNames.indexOf(paramName),keywordArguments.get(paramName));
                        }
                    }
                    for (ASTNode n : other.children) n.parent = other;
                } else other = new ASTVariable(token);
            } else if (isListStart(token)) {
                if (last instanceof ASTVariable || last instanceof ASTFunction || last instanceof ASTListAccessor) {
                    List<String> inBetween = collectContainedTokens(tokens,JavaPythonShadower::isListStart,JavaPythonShadower::isListEnd);
                    List<String> first = new ArrayList<>();
                    List<String> second = new ArrayList<>();
                    boolean range = false;
                    for (int i = 0;i < inBetween.size();i++) {
                        if (isColon(inBetween.get(i))) {
                            range = true;
                        } else if (!range) {
                            first.add(inBetween.get(i));
                        } else {
                            second.add(inBetween.get(i));
                        }
                    }
                    ASTListAccessor accessor = new ASTListAccessor("indexAccess");
                    if (!range) {
                        if (first.isEmpty()) throw new RuntimeException("LID Python: No index in list access.");
                        accessor.first = parseExpression(PointedTokenSpace.fromSingleLine(first),definitions,linkedSymbolicFunctions);
                    } else {
                        accessor.range = true;
                        if (first.isEmpty() && second.isEmpty()) throw new RuntimeException("LID Python: No index in list access.");
                        if (first.isEmpty()) accessor.first = null;
                        else accessor.first = parseExpression(PointedTokenSpace.fromSingleLine(first),definitions,linkedSymbolicFunctions);
                        if (second.isEmpty()) accessor.second = null;
                        else accessor.second = parseExpression(PointedTokenSpace.fromSingleLine(second),definitions,linkedSymbolicFunctions);
                    }
                    other = accessor;
                } else {
                    List<ASTNode> elements = collectContainedList(tokens,JavaPythonShadower::isListStart,JavaPythonShadower::isListEnd,definitions,linkedSymbolicFunctions);
                    ASTList list = new ASTList("list");
                    list.elements = elements;
                    other = list;
                }
            } else if (isOpenBracket(token)) {
                List<ASTNode> inner = collectContainedList(tokens,JavaPythonShadower::isOpenBracket,JavaPythonShadower::isClosedBracket,definitions,linkedSymbolicFunctions);
                if (inner.isEmpty()) throw new RuntimeException("LID Python: Brackets empty.");
                if (inner.size() == 1 && (tokens.peekPrev(2) == null || !isComma(tokens.peekPrev(2)))) {
                    other = inner.get(0);
                }
                else {
                    ASTTuple tuple = new ASTTuple("tuple");
                    tuple.elements.addAll(inner);
                    other = tuple;
                }
            } else if (isString(token)) {
                other = new ASTString(token.substring(1,token.length()-1));
            } else throw new RuntimeException("LID Python: Invalid Expression, token '"+token+"'.");

            if (tokens.hasNext()) { // Inline if statement
                String nextToken = tokens.peek();
                if (startOfIfStatement(nextToken)) {
                    tokens.next();
                    List<String> condition = collectTokensUntil(tokens,JavaPythonShadower::startOfElse);
                    ASTNode trueRet = other;
                    ASTNode cod = parseExpression(PointedTokenSpace.fromSingleLine(condition),definitions,linkedSymbolicFunctions);
                    tokens.next();
                    ASTNode falseRet = parseExpression(tokens,definitions,linkedSymbolicFunctions);
                    ASTConditional conditional = new ASTConditional("ternary");
                    conditional.condition = cod;
                    conditional.trueValue = trueRet;
                    conditional.falseValue = falseRet;
                    other = conditional;
                }
            }

            if (head == null) head = other;
            else head = pushToAST(head, other,definitions);
            last = other;
        }
        return head;
    }
    // TODO: variable calling using keywords doesn't work on a variable which points to the function

}
